---
title: "Introduction to rtry"
output:
  # word_document:
  #   toc: true
  #   toc_depth: 3
  #   number_sections: true
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Introduction to rtry}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

***

# Overview

`rtry` is an R package to support the application of plant trait data providing easily applicable functions for the basic steps of data preprocessing, e.g. data import, data exploration, selection of columns and rows, excluding trait data according to different attributes, long- to wide-table transformation, data export, and geocoding. The `rtry` package is designed to support the preprocessing of data released from the TRY Plant Trait Database, but is also applicable for other trait data.

The TRY database (https://www.try-db.org/TryWeb/Home.php) has been designed as an integrated database for all kinds of plant traits and provides unprecedented coverage of plant traits. In addition to the trait values the TRY database offers rich and harmonized information to facilitate excluding of trait data according to different aspects, e.g. exposition (natural environment, growth chambers, etc.), georeference, or sampling date. However, the size of datasets released from TRY is often too large to be handled by spreadsheets like Microsoft Excel and the relevant information for trait data excluding is contained at different places of the released data, e.g. trait names, species names, ancillary data representing context information, units of trait data, and identifiers for duplicates and outliers. Therefore, finding all relevant information for trait data excluding is not straightforward without in-depth knowledge of the inherent data structure.

We developed the `rtry` package to support data preprocessing, i.e. data excluding, taking advantage of the relevant features of the TRY database. The package is supposed to be applicable without advanced knowledge of the R software or the data structure released from TRY.

Additional vignettes providing example workflows for trait data preprocessing and geocoding are available at:

-   [The general workflow](rtry-workflow-general.html)

    -   An example workflow setup to demonstrate how to use the `rtry` package to preprocess the data exported from the TRY database
    -   Covers most of the `rtry` functions from importing and exploring to binding multiple data frames, as well as selecting or excluding specific data, removing duplicates, and finally exporting the preprocessed data

-   [Perform (reverse) geocoding](rtry-workflow-geocoding.html)

    -   An example workflow setup to demonstrate how to use the `rtry` package to perform geocoding and reverse geocoding on the TRY data
    -   Covers mainly the functions `rtry_geocoding` and `rtry_revgeocoding`


The `rtry` package is the first product of the TRY R project, which is maintained on the MPI-BGC-Functional-Biogeography GitHub repository: https://github.com/MPI-BGC-Functional-Biogeography/rtry. The project is supposed to support the development of R tools for trait data preprocessing and analysis, starting with tools to preprocess trait data released from the TRY database. Further developments of the package will also be available on this open access GitHub repository.

<br>

***

# The TRY data format

Through the TRY Data Portal (https://www.try-db.org/TryWeb/dp.php; Kattge et al. 2020), trait data are released in a table-delimited long-table format as zipped text file (`.txt`) with `Latin-1` encoding. Each row of the long-table represents either a trait record or a record with context information (i.e. ancillary data).


Different records belonging to the same observation (e.g. trait value and the respective records for latitude and longitude of the sampling site, and the sampling date) are combined across records by the `ObservationID` (see Table below) (Madin et al. 2007, Kattge et al. 2011b).

In TRY version 5, there are 27 columns, with a header in the first row of the text file (see Table below). Datasets released from other version of the TRY database may contain different numbers of columns. However, this is taken into account within the `rtry` package, as it provides a function for detailed data exploration (`rtry_explore()`, for details please refer to the section "The `rtry` package" below).

Table: Column headers of data released from the TRY version 5

|      | Column         | Comment                                                      |
| ---- | -------------- | ------------------------------------------------------------ |
| 1.   | LastName       | Surname of data contributor                                  |
| 2.   | FirstName      | First name of data contributor                               |
| 3.   | DatasetID      | Unique identifier of contributed dataset                     |
| 4.   | Dataset        | Name of contributed dataset                                  |
| 5.   | SpeciesName    | Original name of species                                     |
| 6.   | AccSpeciesID   | Unique identifier of consolidated species name               |
| 7.   | AccSpeciesName | Consolidated species name                                    |
| 8.   | ObservationID  | Unique identifier for each observation                       |
| 9.   | ObsDataID      | Unique identifier for each record                            |
| 10.  | TraitID        | Unique identifier for traits (only if the record is a trait) |
| 11.  | TraitName      | Name of trait (only if the record is a trait)                |
| 12.  | DataID         | Unique identifier for each sub-trait or context information  |
| 13.  | DataName       | Name of sub-trait or context information                     |
| 14.  | OriglName      | Original name of sub-trait or context information            |
| 15.  | OrigValueStr   | Original value as text string                                |
| 16.  | OrigUnitStr    | Original unit as text string                                 |
| 17.  | ValueKindName  | Value kind (single measurement, mean, median, etc.)          |
| 18.  | OrigUncertaintyStr | Original uncertainty as text string                      |
| 19.  | UncertaintyName | Kind of uncertainty (standard deviation, standard error, etc.) |
| 20.  | Replicates      | Count of replicates                                          |
| 21.  | StdValue        | Standardized value: available for standardized traits        |
| 22.  | UnitName        | Standard unit: available for standardized traits             |
| 23.  | RelUncertaintyPercent | Relative uncertainty in %                              |
| 24.  | OrigObsDataID   | Unique identifier for duplicate entries                      |
| 25.  | ErrorRisk       | Indication for outliers: distance to mean in standard deviations |
| 26.  | Reference       | Reference to be cited if trait record is used in analysis    |
| 27.  | Comment         | Explanation for the `OriglName` in the contributed dataset |
| 28.  | V28             | Empty, an artifact due to different interpretation of column separator by MySQL and R |

<br>

***

# The `rtry` package

The `rtry` package provides a set of easily applicable functions to facilitate the preprocessing of plant trait data, e.g. data import, data exploration, selection of columns and rows, excluding trait data according to different attributes, geocoding, long- to wide-table transformation, and data export. The `rtry` package has been developed with a focus on data released from the TRY database. However, the `rtry` package is supposed to be applicable without advanced knowledge of the R software and without in-depth knowledge of all aspects of the TRY data structure.

<br>

## Sources of `rtry`

There are three sources where users can download the `rtry` package and the relevant documentation.

**CRAN**

The `rtry` package is available on the CRAN repository. This is the recommended option to obtain the latest version of the package.

**GitHub Repository**

As mentioned before, the TRY R project is an open-source project that can be found on the MPI-BGC-Functional-Biogeography GitHub repository: https://github.com/MPI-BGC-Functional-Biogeography/rtry.

- Code: the source code for the released package, as well as the developing functions
- Wiki: the documentation of the package and the example workflows, as well as some additional information related to the TRY R project
- Issues: users can use this platform to report bugs or provide feature suggestions

Developers are also welcome to contribute to the package.

**Nextcloud**

We have set up a shared directory on the MPI-BGC Nextcloud, where users can obtain the source package and the corresponding documentation, as well as the sample data and example workflows. Pre-prepared folder structure for the two example workflows can be found.

- Link: https://nextcloud.bgc-jena.mpg.de/s/RMd5kqg7tRWXpae
- Password: `mpi-bgc-rtry`

The overview of the folder structure is as follow. If the user wishes to try out the package with the provided example scripts, it is advised to download the entire `examples` directory and maintain the folder structure:

```markdown
.
├── build					# Source files for the rtry package
│   ├── rtry_x.x.x		# Source package
├── docs					# Documentation files
├── examples				# Scripts of example workflow
│   ├── input				# Input files needed for testing
└── README.md
```

<br>

## R environment

R 4.0.3 was used to develop and build the `rtry` package, and this is the minimum version required to use the package.

The latest version of R can be downloaded from CRAN, a network of ftp and web servers around the world that store the code and documentation of R: https://cran.r-project.org/

In case RStudio is used, we also recommend to use the latest version of RStudio when using the package. The released version of RStudio, an integrated development environment (IDE) designed for productive R programming, can be found at https://www.rstudio.com/products/rstudio/download/, it is sufficient to use the free and open source version of RStudio Desktop.

<br>

## Memory requirement

Since R reads the entire dataset into the memory all at once and because R holds the objects it is using in virtual memory, memory capacity is important when loading large dataset (>500,000 trait records) released from the TRY database.

When a memory issue occurs, users could either use a machine with more memory (RAM) installed, or they could request smaller datasets (instead of one large dataset) and import the datasets into R separately. It is also possible to use `memory.limit()` to increase the default memory, e.g. `memory.limit(size=2500)`, where the size is in MB. Note that you need to be using 64-bit in order to take real advantage of this.

<br>

## Installation guide

The installation of the `rtry` package can be performed through the RStudio console.

First, install all the dependencies with the command.

```R
install.packages(c("data.table", "dplyr", "tidyr", "jsonlite", "curl"))
```

Once installation is completed, the message `The downloaded source packages are in <path>` should be seen.

Next, install the `rtry` package with the command:

From CRAN:

```R
install.packages("rtry")
```

Else, if user downloaded the source package (`.tar.gz`) from the GitHub repository or Nextcloud:

```R
install.packages("<path_to_rtry.tar.gz>", repos = NULL, type = "source")
```

Note: The character `\` is used as escape character in R to give the following character special meaning (e.g. `\n` for newline, `\t` for tab, `\r` for carriage return and so on). Therefore, for Windows users, it is important to replace the `\` in the file path with `/` in order for R to correctly understand the input path.

You may ignore the warning message "`Rtools is required to build R packages but is not currently installed`" if it appears.

Once the installation is completed, the `rtry` package needs to be loaded with the command:

```R
library(rtry)
```

<br>

## Update the `rtry` package

To update the `rtry` package to a newer version in the future, simply restart RStudio and use the same installation command.

From CRAN:

```R
# Remember to restart RStudio first
install.packages("rtry")
```

Else,  if the user downloaded the latest source package (`.tar.gz`) of `rtry` from the GitHub repository or Nextcloud:

```R
# Remember to restart RStudio first
install.packages("<path_to_rtry.tar.gz>", repos = NULL, type = "source")
```

You may ignore the warning message "`Rtools is required to build R packages but is not currently installed`" if it appears.

<br>

## R commands to retrieve information about the package

### Check `rtry` version

To check the version of the loaded `rtry` package:

```R
packageVersion("rtry")
```

<br>

### Obtain documentations of the `rtry` package

To get an overview of the `rtry` package and the corresponding documentations:

```R
help(package = "rtry")
```

This command displays an index of all help pages with the vignettes, functions, and data of the `rtry` package on the `Help` panel on RStudio.

<br>

### Obtain documentation for a specific function

Inside the `rtry` package, each function has its corresponding documentation providing a brief description of the function, and explanation for each argument. For the documentation of a specific function, such as `rtry_import()`, type a `?` in front of the function name:

```R
?rtry_import
```

To view the R code underlying the function, the `View` function can be used within R or RStudio:

```R
View(rtry_import)
```

For the source code with comments, go to your local R directory, then look for the `rtry/R` directory which should be located inside the `library` directory. A `.R` file for each function is provided. Else the source code is also provided on the GitHub repository.

<br>

### Obtain documentation for a sample data

Several sample datasets have been provided within the `rtry` package. To obtain the documentation of the data such as `data_TRY_15160`, use the following command:

```R
?data_TRY_15160
```

To view the sample data, call the `View` function:

```R
View(data_TRY_15160)
```

This invokes a data viewer window immediately and it does not import the data. For more information about the sample data within the package and how to import them, see the section "Sample datasets within the `rtry` package" below.

There are more ways to explore a dataset in R, some of which can be seen below:

```R
# Show the dimensions of the dataset
dim(data_TRY_15160)

# Show the column names
colnames(data_TRY_15160)

# Show first 100 rows
data_TRY_15160[1:100,]

# Show first 10 rows
head(data_TRY_15160)

# Show last 10 rows
tail(data_TRY_15160)

# Produce result summaries of various model fitting functions
summary(data_TRY_15160)
```


<br>

### Obtain vignettes of the package

To open a list of vignettes for the `rtry` package:

```R
browseVignettes("rtry")
```

To directly view a vignette (e.g. `rtry-introduction`) of the `rtry` package from the `Help` panel:

```R
vignette("rtry-introduction")
```

<br>

---

## Functionality of the `rtry` package

The `rtry` package is a compilation of functions developed to support the preprocessing of trait data, foremost if received via the TRY database. To enable easy application, some attributes within the `rtry` package are specified for the structure and column names used in the data released from TRY.

To realize the full functionality of `rtry` for other trait datasets, these should be transformed to the data structure used in the data releases from the TRY database: long table format specifically including the column names of the IDs: `ObservationID`, `ObsDataID`, `TraitID`, `DataID`, `OrigObsDataID`, `AccSpeciesID`, `DatasetID`, and the columns `StdValue`, `OrigValueStr` and `ErrorRisk`. Different measurements (traits and ancillary data) are combined via the `ObservationID`. If additional datasets are used with the TRY data, these need to be consistent with the respective data from TRY.

<br>

### Function default arguments

There are some implicit aspects with respect to writing commands in R that make commands short and convenient. For example, the `rtry_import` function is by default set to fit the data released from TRY, and is specified as:

```R
rtry_import(
  input,
  separator = "\t",
  encoding = "Latin-1",
  quote = "",
  showOverview = TRUE
)
```

The example above is copied from the reference manual and includes the function name and all possible arguments for this function.

If the argument is followed by "`=`", it means a default value is specified. Else it awaits user input at all times. If an argument is specified by default, it does not need to be explicitly written when calling the function. Therefore, importing data released from TRY is as simple as:

```R
data <- rtry_import(input_path)
```

However, to import other file formats, the arguments may need to be explicitly defined. For example, to import a data file with comma separated values (`.csv`):

```R
data <- rtry_import(input_path,
          separator = ",",
          encoding = "UTF-8",
          quote = "\"",
          showOverview = TRUE)
```

By explicitly defining the arguments, the default values are overridden.

In R, the order of operations when given a sequence of arguments is:

1. Check for exact match for a named argument, e.g. `separator`.
2. Check for a partial match, e.g. `sep`.
3. Check for a positional match, according to the sequence given in the reference manual. In this case, a user would just specify the values of the arguments without providing the argument name itself, e.g. `data <- rtry_import(input_path, ",", "UTF-8", "\"", TRUE)`.

<br>

### Functions within the `rtry` package

Inside the `rtry` package, we use a function naming convention where each function begins with the prefix `rtry_` followed by what the specific function does. The `rtry` package consists of the following functions:

- `rtry_import`: Import data
- `rtry_explore`: Explore data
- `rtry_bind_col`: Bind data by columns
- `rtry_bind_row`: Bind data by rows
- `rtry_join_left`: Left join for two data frames
- `rtry_join_outer`: Outer join for two data frames
- `rtry_select_col`: Select columns
- `rtry_select_row`: Select rows
- `rtry_select_anc`: Select ancillary data in wide table format
- `rtry_exclude`: Exclude data
- `rtry_rm_col`: Remove columns
- `rtry_rm_dup`: Remove duplicates in data
- `rtry_trans_wider`: Transform data from long to wide table
- `rtry_export`: Export preprocessed data
- `rtry_geocoding`: Perform geocoding
- `rtry_revgeocoding`: Perform reverse geocoding

Detailed description of each function can be found in the reference manual (`.pdf`) generated by CRAN, or via the command:

```R
# For the documentation of a specific function (e.g. `rtry_import())
# Type a `?` in front of the function name
?rtry_import

# For the underlying R code, use the `View` function
View(rtry_import)
```

<br>

## Handling of data within `rtry`

Within `rtry`, data are stored and used as tables (frames) with features fulfilling the requirements of both classes in R: `data.table` and `data.frame`. The `rtry_import` function stores data in data format consistent with both classes `data.table` and `data.frame`. Functions used for preprocessing can use both formats as input format and they do not change the format for the output. Only the output of the functions `rtry_explore`, `rtry_trans_wider`, `rtry_geocoding` and `rtry_revgeocoding` is of format `data.frame` only.

<br>

## Sample datasets within the `rtry` package

Several sample datasets have been provided within the `rtry` package in both `.rda` format (a format designed for use with R) and in raw data format (`.txt` or `.csv`).

Detailed description of each dataset can be found in the reference manual (`.pdf`) generated by CRAN, or via the command:

```R
# For the documentation of a specific dataset (e.g. `data_TRY_15160` or `locations`)
# Type a `?` in front of the name of the dataset
?data_TRY_15160
?data_locations

# To view the dataset by invoking the data viewer
# Use the `View` function
View(data_TRY_15160)
View(data_locations)
```

To load a dataset (`.rda` format) from the `rtry` package and load the dataset into the workspace:

```R
data(data_TRY_15160)
data(data_locations)
```

This `data` function creates an object in the `envir` environment (by default the user's workspace) replacing any which already existed. (Note: All `rtry` sample datasets in `.rda` format are in the package folder `data`.)

To access the address of a dataset in its raw data format, the following R command will return the exact path:

```R
# To obtain the exact path of the raw dataset within the package
system.file("testdata", "data_TRY_15160.txt", package = "rtry")
system.file("testdata", "data_locations.csv", package = "rtry")

# Expected return on a Mac OS is similar to this:
## [1] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rtry/testdata/data_TRY_15160.txt"
## [1] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rtry/testdata/data_locations.csv"

# Expected return on a Windows OS is similar to this:
## [1] "C:/Program Files/R/R-4.0.3/library/rtry/testdata/data_TRY_15160.txt"
## [1] "C:/Program Files/R/R-4.0.3/library/rtry/testdata/data_locations.csv"
```

Note: All `rtry` sample datasets in their raw data format are in the package folder `testdata`.

<br>

***

# Data license

The `rtry` package is distributed under the [CC BY 4.0](https://github.com/MPI-BGC-Functional-Biogeography/rtry/blob/main/LICENSE.md) license, with a remark that the (reverse) geocoding functions provided within the package used the Nominatim developed with OpenStreetMap. Despite the API and the data provided are free to use for any purpose, including commercial use, note that they are governed by the [Open Database License (ODbL)](https://wiki.osmfoundation.org/wiki/Licence).

<br>

***

# Authorship guidelines

> reference for the `rtry` package, pending CRAN submission

<br>

***

# References

Kattge, J., S. Díaz, S. Lavorel, I. C. Prentice, P. Leadley, G. Bönisch, E. Garnier (2011a). "TRY - a global database of plant traits." <u>Global Change Biology</u> **17**(9): 2905-2935.

Kattge, J., K. Ogle, G. Bönisch, S. Díaz, S. Lavorel, J. Madin, K. Nadrowski, S. Nöllert, K. Sartor and C. Wirth (2011b). "A generic structure for plant trait databases." <u>Methods in Ecology and Evolution</u> **2**(2): 202-213.

Kattge, J., G. Bönisch, S. Díaz, S. Lavorel, I. C. Prentice, P. Leadley, S. Tautenhahn (2019). "TRY plant trait database – enhanced coverage and open access." <u>Global Change Biology</u> **26**(1): 119-188.

Madin, J., S. Bowers, M. Schildhauer, S. Krivov, D. Pennington and F. Villa (2007). "An ontology for describing and synthesizing ecological observation data." <u>Ecological Informatics</u> **2**: 279-296.
